package pojo;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Apartment implements java.io.Serializable {

	private Integer aid;
	private String aname;
	private Integer acost;
	private String atype;
	private String adesc;
	private String address;
	public Apartment() {
	}

	public Apartment(  String aname, Integer acost,
			 String atype, String adesc,String address ) {
		
		this.aname = aname;
		this.acost = acost;
		this.atype = atype;
		this.adesc = adesc;
		this.address = address;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	public Integer getAcost() {
		return this.acost;
	}

	public void setAcost(Integer acost) {
		this.acost = acost;
	}

	public String getAtype() {
		return this.atype;
	}

	public void setAtype(String atype) {
		this.atype = atype;
	}

	public String getAdesc() {
		return this.adesc;
	}

	public void setAdesc(String adesc) {
		this.adesc = adesc;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	
	

	

	
	
}
