package pojo;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Fees implements java.io.Serializable {

	private Integer id;
	private String course;
	private String fee;
	
	public Fees() {
	}

	public Fees( String course, String fee) {
		
		this.course = course;
		this.fee = fee;
	}
	
	

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getcourse() {
		return this.course;
	}

	public void setcourse(String course) {
		this.course = course;
	}

	public String getfee() {
		return this.fee;
	}

	public void setfee(String fee) {
		this.fee = fee;
	}

	
	
	
}
