package pojo;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Packg implements java.io.Serializable {

	private Integer id;
	private String pkname;
	private Integer pkcost;
	private String pkdur;
	private String pkdesc;
	public Packg() {
	}

	public Packg(  String pkname, Integer pkcost,
			Date mdate, String pktype, String pkdesc) {
		
		this.pkname = pkname;
		this.pkcost = pkcost;
		this.pkdur = pktype;
		this.pkdesc = pkdesc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer Id) {
		this.id = Id;
	}

	public String getPkname() {
		return this.pkname;
	}

	public void setPkname(String pkname) {
		this.pkname = pkname;
	}

	public Integer getPkcost() {
		return this.pkcost;
	}

	public void setPkcost(Integer pkcost) {
		this.pkcost = pkcost;
	}

	public String getPkdur() {
		return this.pkdur;
	}

	public void setPkdur(String pkdur) {
		this.pkdur = pkdur;
	}

	public String getPkdesc() {
		return this.pkdesc;
	}

	public void setPkdesc(String pkdesc) {
		this.pkdesc = pkdesc;
	}

	

	

	

	
	
}
