package pojo;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sId;
	private String fname;
	private String mname;
	private String lname;
	private String email;
	private Date dob;
	private String gender;
	private String contactno;
	private String address;
	private String course;
	public Student() {
	}

	public Student( String fname, String mname, String lname,
			String email, String password, Date dob, String gender,
			String contactno, String address, String course) {
		
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.email = email;
		
		this.dob = dob;
		this.gender = gender;
		this.contactno = contactno;
		this.address = address;
		this.course = course;
	}

	public Student( String fname, String mname, String lname,
			String email, String password, Date dob, String gender,
			String contactno, String address, Integer rgFirstattemptflag,
			Set studprojects, Set leavemasters) {
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.email = email;
		this.dob = dob;
		this.gender = gender;
		this.contactno = contactno;
		this.address = address;
		
	}

	public Integer getsId() {
		return this.sId;
	}

	public void setsId(Integer sId) {
		this.sId = sId;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getcourse() {
		return this.course;
	}

	public void setcourse(String course) {
		this.course = course;
	}
	
}
