package pojo;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private Integer id;
	private String tname;
	private Integer tcost;
	private String tdur;
	private String tdesc;
	public Test() {
	}

	public Test(  String mname, Integer mcost,
			Date mdate, String mtype, String mdesc) {
		
		this.tname = mname;
		this.tcost = mcost;
		this.tdur = mtype;
		this.tdesc = mdesc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer Id) {
		this.id = Id;
	}

	public String gettname() {
		return this.tname;
	}

	public void settname(String tname) {
		this.tname = tname;
	}

	public Integer gettcost() {
		return this.tcost;
	}

	public void settcost(Integer tcost) {
		this.tcost = tcost;
	}


	public String gettdur() {
		return this.tdur;
	}

	public void settdur(String tdur) {
		this.tdur = tdur;
	}

	public String gettdesc() {
		return this.tdesc;
	}

	public void settdesc(String tdesc) {
		this.tdesc = tdesc;
	}

	

	

	
	
}
